### PR TITLE
added e2e tests

### PR DESCRIPTION
**Pull request by STEPHINRACHEL**
ping @psturc @grdryn @jhellar

### CODE REVIEW

**Review by STEPHINRACHEL — COMMENTED** [review]
ping @psturc @jhellar @b1zzu @grdryn

**Comment by jhellar** [comment]
@STEPHINRACHEL I'm not that familiar with these e2e tests, but quickly looking at them they looks good to me. But just looking at jenkins build and Jenkinsfile - they are not actually executed. Should the `Build test binary` and `Test operator` stages be enabled now?

**Comment by psturc** [comment]
@STEPHINRACHEL https://github.com/aerogear/app-metrics-operator/blob/master/Jenkinsfile#L101-L131
otherwise LGTM

**Comment by jhellar** [comment]
@STEPHINRACHEL looking at the build, there are some missing pieces from dependencies. I was able to `make test/compile` by running `dep ensure` before that - it installed the missing stuff. I would say that running this command and committing those changes should solve the issue.

**Review by jhellar — APPROVED** [review]

**Review by psturc — APPROVED** [review]
LGTM

**Pull request merged**
